version: "3"

services:
  yacht:
    image: selfhostedpro/yacht
    container_name: yacht
    volumes:
      - ./config:/config
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
