version: '3'

services:
  portainer:
    networks:
      - proxy
    labels:
      - traefik.enable=true
      - traefik.http.services.portainer.loadbalancer.server.port=9000
      - traefik.http.routers.portainer.entrypoints=web
      - traefik.http.routers.portainer.rule=Host(`${FQDN}`)
      - traefik.http.middlewares.portainer-https-redirect.redirectscheme.scheme=websecure
      - traefik.http.routers.portainer.middlewares=portainer-https-redirect
      - traefik.http.routers.portainer-secure.entrypoints=websecure
      - traefik.http.routers.portainer-secure.rule=Host(`${FQDN}`)
      - traefik.http.routers.portainer-secure.tls=true
      - traefik.http.routers.portainer-secure.tls.certresolver=letsencrypt

networks:
  proxy:
    external: true
